In [1]:
import re

import pandas as pd
import pickle

from pandas import read_pickle

df = pd.read_excel('Grades.xls',sheet_name="23-24 1к 1п")
to_drop = []
for key in df.keys():
    i = 1
    while not isinstance(df[key][i],str):
        i+=1
        if i == len(df[key]):
            break
    if i==len(df[key]):
        to_drop.append(key)
    elif df[key][i][0] in '+-':
        to_drop.append(key)
#print(to_drop)
df.drop(to_drop,axis=1,inplace=True)
df

,Иностранный язык,История России,Основы проектной деятельности,Основы российской государственности,Аналитическая геометрия,Высшая алгебра,Дискретная математика и теория алгоритмов,История России.1,Математическая логика,Математический анализ,Программирование
0,,,,,,,,,,,
1,5(25.05.21)\n5(15.09.22),5(24.12.20)\n5(15.09.22),5(26.05.21)\n5(15.09.22),NaN,5(15.01.21)\n2(22.06.21)\n5(29.06.21)\n5(15.09...,3(20.01.21)\nн(08.06.21)\nн(02.07.21)\n3(22.09...,2(25.01.21)\n5(11.02.21)\n5(15.09.22),NaN,4(18.06.21)\n4(15.09.22),5(11.01.21)\nн(02.06.21)\nн(01.07.21)\n3(13.09...,3(14.06.21)\n3(15.09.22)
2,5(28.05.24),5(25.12.23),5(29.05.24),5(29.12.23),5(26.01.24)\n4(22.06.24),4(16.01.24)\n5(10.06.24),3(22.01.24),5(24.06.24),4(14.06.24),5(11.01.24)\n4(05.06.24),5(18.06.24)
3,4(28.05.24),4(27.12.23),5(29.05.24),5(29.12.23),5(25.01.24)\n5(08.06.24),5(20.01.24)\n5(04.06.24),5(16.01.24),4(10.06.24),5(17.06.24),5(11.01.24)\n5(13.06.24),5(21.06.24)
4,4(28.05.24),5(27.12.23),5(29.05.24),5(29.12.23),2(25.01.24)\n4(31.01.24)\n2(21.06.24)\n2(26.06...,4(15.01.24)\n2(08.06.24)\n3(02.07.24),3(20.01.24),5(24.06.24),2(13.06.24)\n2(03.07.24)\n3(26.09.24),2(10.01.24)\n3(02.02.24)\n4(04.06.24),4(17.06.24)
...,...,...,...,...,...,...,...,...,...,...,...
133,4(28.05.24),4(27.12.23),4(29.05.24),5(29.12.23),2(25.01.24)\n5(31.01.24)\n4(08.06.24),4(20.01.24)\n5(04.06.24),5(16.01.24),4(10.06.24),5(17.06.24),3(11.01.24)\n4(13.06.24),4(21.06.24)
134,4(30.05.23),5(22.12.22),NaN,NaN,5(21.01.23)\n5(17.06.23),5(16.01.23)\n5(21.06.23),5(25.01.23),NaN,5(13.06.23),5(11.01.23)\n5(07.06.23),NaN
135,NaN,н(25.12.23),NaN,н(29.12.23),NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,NaN,4(25.12.23),NaN,4(29.12.23),н(26.01.24),н(16.01.24),н(22.01.24),NaN,NaN,н(11.01.24),NaN
137,NaN,н(25.12.23)\nн(31.01.24)\nн(19.02.24),NaN,н(29.12.23)\nн(29.01.24)\nн(15.02.24),н(26.01.24)\nн(31.01.24)\nн(29.02.24),н(16.01.24)\nн(29.01.24)\nн(21.02.24),н(22.01.24)\nн(01.02.24)\nн(15.02.24),NaN,NaN,н(11.01.24)\nн(02.02.24)\nн(28.02.24),NaN

In [15]:
cell = df['Аналитическая геометрия'][1]
dates = [int(j.split(".")[1]) for j in re.findall(r'\((.*?)\)',cell)]
grade_cell = [j[0] for j in re.findall(r'.\(',cell)]
print(dates)
print(grade_cell)
j = 1
while grade_cell[j-1] not in '345'and j<len(grade_cell):
    j += 1
if j>=len(grade_cell): date_2 = []
else: date_2 = [dates[j]]
dates_valid = [dates[0]]+date_2
print(dates_valid)

[1, 6, 6, 9]
['5', '2', '5', '5']
[1, 6]

In [41]:
df_semester1 = {}
df_semester2 = {}
for key in df.keys():
    i = 1
    while not isinstance(df[key][i],str):
        i+=1
    dates = [int(j.split(".")[1]) for j in re.findall(r'\((.*?)\)', df[key][i])]
    grade_cell = [j[0] for j in re.findall(r'.\(',df[key][i])]
    j = 1
    while grade_cell[j-1] not in '345'and j<len(grade_cell):
        j += 1
    if j>=len(grade_cell): date_2 = []
    else: date_2 = [dates[j]]
    dates_valid = [dates[0]]+date_2
    #print(dates)
    if any(item in dates_valid for item in (11,12,1,2,3,4)):
        df_semester1[key] = []
        for cell in df[key]:
            #print(cell)
            if isinstance(cell,float):
                df_semester1[key].append(cell)
            else:
                if len(cell)<2:
                    df_semester1[key].append(float("nan"))
                    continue
                grade_cell = [j[0] for j in re.findall(r'.\(',cell)]
                #print(grade_cell)
                j = 0
                while j<len(grade_cell) and grade_cell[j] not in '345':
                    j += 1
                j = min(j,len(grade_cell)-1)
                if grade_cell[j].isdigit():
                    df_semester1[key].append(int(grade_cell[j]))
                else:
                    df_semester1[key].append(float("nan"))
    if any(item in dates for item in (5,6,7,8,9,10)):
        df_semester2[key] = []
        for cell in df[key]:
            if isinstance(cell,float):
                df_semester2[key].append(cell)
            else:
                if len(cell)<2:
                    df_semester2[key].append(float("nan"))
                    continue
                grade_cell = [j[0] for j in re.findall(r'.\(',cell)]
                #print(len(cell),cell)
                if grade_cell[-1].isdigit():
                    df_semester2[key].append(int(grade_cell[-1]))
                else:
                    df_semester2[key].append(float("nan"))

df_semester1 = pd.DataFrame(df_semester1)
df_semester2 = pd.DataFrame(df_semester2)

data = {"semester1":df_semester1,"semester2":df_semester2}

with open('23-24_1c1p.pkl', 'wb') as file:
    pickle.dump(data, file)

data = {}

with open('23-24_1c1p.pkl', 'rb') as file:
    data = pickle.load(file)
#print(df_semester1)
#print(df_semester2)

In [42]:
data['semester1']

,История России,Основы российской государственности,Аналитическая геометрия,Высшая алгебра,Дискретная математика и теория алгоритмов,Математический анализ
0,NaN,NaN,NaN,NaN,NaN,NaN
1,5.0,NaN,5.0,3.0,5.0,5.0
2,5.0,5.0,5.0,4.0,3.0,5.0
3,4.0,5.0,5.0,5.0,5.0,5.0
4,5.0,5.0,4.0,4.0,3.0,3.0
...,...,...,...,...,...,...
133,4.0,5.0,5.0,4.0,5.0,3.0
134,5.0,NaN,5.0,5.0,5.0,5.0
135,NaN,NaN,NaN,NaN,NaN,NaN
136,4.0,4.0,NaN,NaN,NaN,NaN
137,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
data['semester2']

,Иностранный язык,История России,Основы проектной деятельности,Аналитическая геометрия,Высшая алгебра,Дискретная математика и теория алгоритмов,История России.1,Математическая логика,Математический анализ,Программирование
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.0,5.0,5.0,5.0,3.0,5.0,NaN,4.0,5.0,3.0
2,5.0,5.0,5.0,4.0,5.0,3.0,5.0,4.0,4.0,5.0
3,4.0,4.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0
4,4.0,5.0,5.0,3.0,3.0,3.0,5.0,3.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...
133,4.0,4.0,4.0,4.0,5.0,5.0,4.0,5.0,4.0,4.0
134,4.0,5.0,NaN,5.0,5.0,5.0,NaN,5.0,5.0,NaN
135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
data['semester1'].to_excel('semester1.xlsx')
data['semester2'].to_excel('semester2.xlsx')